### ISSUE TITLE
Songs stop loading in the menu.

### ISSUE THREAD

**Issue by FlorisFireball** [Idlebawb/ScorePercentage#3]
Upon game startup, you can see a list of the songs, but if you click on any of them, it endlessly loads the mode selection (hard, expert, expert+). Removing the mod fixed this issue.

**Comment by Idlebawb** [comment]
Can you provide a little bit more info?
Game Version, Which ScorePercentage Version and a Logfile.

Sounds like you're either using a wrong version of the mod for your game version or an incompatibility with another mod.
Can't really say tho without a logfile.

**Comment by Idlebawb** [comment]
Well since you opened 2 similar issues on other people's mods, that obviously work fine too and no reply.
I'll assume you're either trolling, or you need to clean up your whole beat saber installation.
